modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

[[mods]] #mandatory
modId="undergardenpatch" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
credits="Thanks for this mod goes to mickelus of Tetra and quek of the Undergarden, for writing all the code I Frankensteined together, and for the help they gave along the way." #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.undergardenpatch]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.undergardenpatch]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.undergardenpatch]]
    modId="tetra"
    mandatory=true
    versionRange="[6.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.undergardenpatch]]
    modId="undergarden"
    mandatory=true
    versionRange="[0.8.5,)"
    ordering="NONE"
    side="BOTH"
