modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="undergardenpatch" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Undergarden/Tetra Patch" #mandatory
credits="Thanks for this mod goes to mickelus of Tetra and quek of the Undergarden, for writing all the code I Frankensteined together, and for the help they gave along the way." #optional
authors="Syric" #optional
description='''
This mod adds Undergarden materials to Tetra, including their effects. Requires Tetra 3.4.0+ and the Undergarden 0.4.0+.
'''

[[dependencies.undergardenpatch]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.undergardenpatch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.undergardenpatch]]
    modId="tetra"
    mandatory=true
    versionRange="[3.4.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.undergardenpatch]]
    modId="undergarden"
    mandatory=true
    versionRange="[0.4.0,)"
    ordering="NONE"
    side="BOTH"
