modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="undergardenpatch" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Tetra/Undergarden Patch" #mandatory
credits="Thanks for this mod goes to mickelus of Tetra and quek of the Undergarden, for writing all the code I Frankensteined together, and for the help they gave along the way." #optional
authors="Syric" #optional
description='''
This mod adds Undergarden materials to Tetra, including their effects. Requires Tetra 4.10.1+ and the Undergarden 0.7.1+.
'''

[[dependencies.undergardenpatch]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.undergardenpatch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.undergardenpatch]]
    modId="tetra"
    mandatory=true
    versionRange="[4.10.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.undergardenpatch]]
    modId="undergarden"
    mandatory=true
    versionRange="[0.7.1,)"
    ordering="NONE"
    side="BOTH"
